version: "1"
rules:                      # Array of rules
  - base: master   # Required. Target branch
    upstream: choreonoid:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: with_irsl_system
    upstream: choreonoid:master
    mergeMethod: merge
### [TODO] add stable
