version: "1"
rules:  # Array of rules
  - base: master   # Required. Target branch
    upstream: choreonoid:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
## irsl/stable (at one point in origin/master)
## irsl/irsl_patch (at one point in origin/master + IRSL_patch)
  - base: stable_with_irsl_patch
    upstream: IRSL-tut:stable
    mergeMethod: merge
  - base: devel
    upstream: choreonoid:master
    mergeMethod: rebase
## removed
#  - base: with_irsl_system
#    upstream: choreonoid:master
#    mergeMethod: merge
## devel (master_with_irsl_patch)
  - base: devel_merge ## backward-compatibility
    upstream: choreonoid:master
    mergeMethod: merge
