#ifndef CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_EXPORTDECL_H
# define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_EXPORTDECL_H

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLIMPORT __declspec(dllimport)
#  define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLEXPORT __declspec(dllexport)
#  define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLLOCAL __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLIMPORT
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLEXPORT
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLLOCAL
#  endif
# endif

# ifdef CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_STATIC
#  define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLAPI
#  define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_LOCAL
# else
#  ifdef CnoidPiecewiseRigidContinuousTrack_EXPORTS
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLAPI CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLEXPORT
#  else
#   define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLAPI CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLIMPORT
#  endif
#  define CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_LOCAL CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_PIECEWISE_RIGID_CONTINUOUS_TRACK_DLLAPI
